---
- hosts: all
  name: Install Laravel Project
  gather_facts: true
  vars_files:
    - ./vars/main.yml
  pre_tasks:
    - name: add fpm containers to inventory
      include: ./container_inventory.yml
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug:
        msg: Nginx Server Name Set to {{ project_name }}.{{ ansible_default_ipv4.address }}.nip.io
    - name: run command in container
      delegate_to: fpm7.2
      raw: php -v
    - name: run command in web container
      delegate_to: web
      raw: nginx -t
    